<div style="margin: 0 auto; text-align: center;">
	<div class="col-12">
		<span class="text-center" style="font-size: 10px;">
			Halaman <span class="pageNumber">@pageNumber</span> dari <span class="totalPages">@totalPages</span>
			Dicetak pada: @php echo now()->format('d M Y H:i:s'); @endphp (autogenerated)
		</span>
	</div>
</div>
