<!DOCTYPE html>
<html lang="en" class="root-text-sm">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="description" content="Dokumen Logbook Tanam-Produksi {{$payload['company'] . ' - ' . $payload['noIjin']}}">
	<meta name="author" content="Sistem Monitoring Wajib Tanam-Produksi Komoditas Hortikultura Strategis">
    <title>Autogenerated Logbook Tanam-Produksi {{$payload['company'] . ' - ' . $payload['noIjin']}} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<style>
		.table-sm th,
		.table-sm td {
		padding: 0.3rem; }

		.root-text-sm{
			font-size: 15px;
		}
		.pagebreak {
			page-break-before: always
		}
		.gm-style-cc {
            display: none;
        }
        /* Alternatif: Memindahkan logo Google keluar layar - ini juga melanggar kebijakan Google */
        .gmnoprint.gm-bundled-control.gm-bundled-control-on-bottom {
            display: none;
        }
	</style>
</head>

<body>
	<div class="main small">
		{{-- <a href="{{route('2024.verifikator.tanam.generateLogbook', $payload['ijin'])}}">Generate PDF</a> --}}
		@foreach($payload['lokasis'] as $lokasi)
			<div class="pagebreak"></div>
			<div class="px-5 py-3">
				<div class="row justify-content-center align-items-start mb-4">
					<div class="col-md-7">
						<div class="logo-text text-center">
							<h6 class="mb-0 fw-bold">PENCATATAN KEGIATAN BUDIDAYA BAWANG PUTIH</h6>
							<p class="mb-0">Realisasi Wajib Tanam-Produksi Bawang Putih</p>
						</div>
					</div>
				</div>
				<div class="row justify-content-center align-items-start mb-2">
					<div class="col-12 d-flex justify-content-between align-items-center">
						{{-- <h6 class="mb-0 fw-bold">Kelompok Tani Mitra: {{$lokasi->pks->masterpoktan->nama_kelompok}}</h6> --}}
						<h6 class="mb-0 fw-bold">Pelaku Usaha: {{$payload['company']}}</h6>
					</div>
				</div>
				<div class="row justify-content-center align-items-start mb-3">
					<div class="col-12 mb-3">
						<input type="hidden" id="latitude-{{ $lokasi->spatial->kode_spatial }}" value="{{ $lokasi->spatial->latitude }}">
						<input type="hidden" id="longitude-{{ $lokasi->spatial->kode_spatial }}" value="{{ $lokasi->spatial->longitude }}">
						<input type="hidden" id="polygon-{{ $lokasi->spatial->kode_spatial }}" value="{{ $lokasi->spatial->polygon }}">
						<div hidden id="myMap-{{$lokasi->kode_spatial}}" style="height: 300px; width: 100%;"></div>
					</div>
					<div class="col-md-6">
						<ul class="list-group">
							<li class="list-group-item">
								<span class="fw-bold">I. Identitas Lahan</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Kode Lokasi</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->kode_spatial}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Latitude</span>
								<span class="col-md-8 ml-auto">: {{$lokasi->spatial->latitude}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Longitude</span>
								<span class="col-md-8 ml-auto">: {{$lokasi->spatial->latitude}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Luas lahan</span>
								<span class="col-md-8 ml-auto">: {{$lokasi->spatial->luas_lahan}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Luas Tanam</span>
								<span class="col-md-8 ml-auto">: {{$lokasi->luas_tanam}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Nama Petani</span>
								<span class="col-md-8 ml-auto">: {{$lokasi->masteranggota->nama_petani}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Nama Petani</span>
								<span class="col-md-8 ml-auto">: {{$lokasi->masteranggota->ktp_petani}}</span>
							</li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="list-group">
							<li class="list-group-item">
								<span class="fw-bold">II. Bantuan sesuai Perjanjian Kerjasama</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Benih</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->benihsize}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Mulsa</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->mulsaSize}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted">Pupuk</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted" style="padding-left: 5mm">Organik</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->organik1 + $lokasi->organik2 + $lokasi->organik3}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted" style="padding-left: 5mm">N P K</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->npk1 + $lokasi->npk2 + $lokasi->npk3}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted" style="padding-left: 5mm">Dolomit</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->dolomit1 + $lokasi->dolomit2 + $lokasi->dolomit3}}</span>
							</li>
							<li class="list-group-item d-flex justify-content-start">
								<span class="col-md-4 text-muted" style="padding-left: 5mm">ZA</span>
								<span class="col-md-8 ml-auto ">: {{$lokasi->za1 + $lokasi->za2 + $lokasi->za3}}</span>
							</li>
						</ul>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-12">
						<span class="fw-bold mb-2">III. Tahapan Kegiatan</span>
						<table class="table table-bordered table-sm">
							<thead>
								<tr>
									<th class="text-center">Kegiatan</th>
									<th class="text-center">Tanggal</th>
									<th class="text-center">Keterangan</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Pengolahan Lahan</td>
									<td class="text-center">{{$lokasi->lahandate ?? ' - '}}</td>
									<td>{{$lokasi->lahancomment ?? ' - '}}</td>
								</tr>
								<tr>
									<td>Persiapan Benih</td>
									<td class="text-center">{{$lokasi->benihDate ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->benihComment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Pemasangan Mulsa</td>
									<td class="text-center">{{$lokasi->mulsaDate ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->mulsaComment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Penanaman</td>
									<td class="text-center">{{$lokasi->tgl_tanam ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->tanamComment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Pemupukan Pertama</td>
									<td class="text-center">{{$lokasi->pupuk1Date ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->pupuk1Comment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Pemupukan Kedua</td>
									<td class="text-center">{{$lokasi->pupuk2Date ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->pupuk2Comment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Pemupukan Ketiga</td>
									<td class="text-center">{{$lokasi->pupuk3Date ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->pupuk3Comment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Pengendalian OPT</td>
									<td class="text-center">{{$lokasi->optDate ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->optComment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Panen/Produksi</td>
									<td class="text-center">{{$lokasi->tgl_panen ?? ' - '}}</td>
									<td>
										<p>{{$lokasi->volume ?? ' - '}}</p>
										<p>{{$lokasi->prodComment ?? ' - '}}</p>
									</td>
								</tr>
								<tr>
									<td>Distribusi Hasil</td>
									<td class="text-center">{{$lokasi->tgl_panen ?? ' - '}}</td>
									<td>
										<p>Untuk Benih: {{$lokasi->vol_benih ?? ' - '}}</p>
										<p>Untuk dijual: {{$lokasi->vol_jual ?? ' - '}}</p>
										<p>{{$lokasi->distComment ?? ' - '}}</p>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		@endforeach
	</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
    </script>


<script>
	$(document).ready(function() {
		function initMap(mapId, latitude, longitude, polygonCoords) {
			const map = new google.maps.Map(document.getElementById(mapId), {
				center: { lat: -2.5489, lng: 118.0149 },
				zoom: 5,
				mapTypeId: google.maps.MapTypeId.SATELLITE,
				draggable: false,
				disableDefaultUI: true,
			});

			createMarker(map, latitude, longitude);
			createPolygon(map, polygonCoords);
		}

		function createMarker(map, latitude, longitude) {
			if (!isNaN(latitude) && !isNaN(longitude)) {
				const position = new google.maps.LatLng(latitude, longitude);
				new google.maps.Marker({
					position: position,
					map: map,
					draggable: false,
				});
				map.setCenter(position);
				map.setZoom(18);
			}
		}

		function createPolygon(map, polygonCoords) {
			if (polygonCoords !== "") {
				try {
					const parsedCoords = JSON.parse(polygonCoords).map(coord => ({ lat: coord.lat, lng: coord.lng }));
					new google.maps.Polygon({
						paths: parsedCoords,
						strokeColor: "#0000FF",
						strokeOpacity: 0.8,
						strokeWeight: 2,
						fillColor: "#FF0000",
						fillOpacity: 0.35,
						map: map,
						editable: false,
						draggable: false,
					});
					const bounds = new google.maps.LatLngBounds();
					parsedCoords.forEach(point => bounds.extend(point));
					map.fitBounds(bounds);
				} catch (e) {
					console.error("Invalid polygon coordinates: ", e);
				}
			}
		}

		// Initialize maps for all elements with dynamic IDs
		$('[id^="myMap-"]').each(function() {
			const mapId = $(this).attr('id');
			const kodeSpatial = mapId.replace('myMap-', '');
			const latitude = parseFloat($(`#latitude-${kodeSpatial}`).val());
			const longitude = parseFloat($(`#longitude-${kodeSpatial}`).val());
			const polygonCoords = $(`#polygon-${kodeSpatial}`).val();

			initMap(mapId, latitude, longitude, polygonCoords);
		});
	});
</script>
</body>

</html>
