<!DOCTYPE html>
<html lang="en" class="root-text-sm">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="description" content="Dokumen Daftar KelompokTani Mitra Wajib Tanam Produksi Bawang Putih">
	<meta name="author" content="Sistem Monitoring Wajib Tanam-Produksi Komoditas Hortikultura Strategis">
    <title>Autogenerated Daftar Kelompoktani Mitra Wajib Tanam Produksi Bawang Putih</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<style>
		.table-sm th,
		.table-sm td {
		padding: 0.3rem; }
		.container.page-cover {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
			width: 100%;
		}
		.root-text-sm{
			font-size: 15px;
		}
		.pagebreak {
			page-break-before: always
		}
		.gm-style-cc {
            display: none;
        }
        /* Alternatif: Memindahkan logo Google keluar layar - ini juga melanggar kebijakan Google */
        .gmnoprint.gm-bundled-control.gm-bundled-control-on-bottom {
            display: none;
        }
	</style>
</head>

<body>
	<div class="main small">
		<div class="container page-cover">
			<div class="row justify-content-between align-items-start">
				<!-- Left Grid: Logo & Text -->
				<div class="col-12 d-flex align-items-start justify-content-center">
					<img src="https://simethris4.test/img/favicon.png" class="mx-2 mt-1 profile-image rounded-circle" style="width: 50px; height:50px" alt="Rijaludin Akbar">
					{{-- <i class="bi bi-ui-checks-grid text-secondary display-4 me-3"></i> --}}
					<div class="logo-text">
						<h1 class="mb-0 fw-bold">DAFTAR KELOMPOKTANI</h1>
						<p class="mb-3 h5 text-muted">MITRA WAJIB TANAM-PRODUKSI BAWANG PUTIH</p>
					</div>
				</div>
			</div>
			<hr>
		</div>

		<div class="pagebreak"></div>
		<div class="container">
			<div class="row mb-3">
				<div class="col-12">
					<span class="fw-bold mb-2">Daftar Lokasi</span>
					<table class="table table-bordered table-sm">
						<thead>
							<tr>
								<th class="text-center">Kelompok</th>
								<th class="text-center">Pimpinan</th>
								<th class="text-center">Kontak</th>
								<th class="text-center">Wilayah</th>
								<th class="text-center">Status</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($payload as $item)
								<tr>
									<td>{{$item->nama_kelompok}}</td>
									<td></td>
									<td></td>
									<td>
										{{$item->desa->nama_desa}} - {{$item->kecamatan->nama_kecamatan}}, <br>
										{{$item->kabupaten->nama_kab}} - {{$item->provinsi->nama}}
									</td>
									<td></td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous">
    </script>


<script>
</script>
</body>

</html>
