<?php

namespace App\Http\Controllers\Admin\Thn2024;

use App\Http\Controllers\Controller;
use App\Models2024\ForeignApi;
use App\Models2024\Lokasi;
use App\Models2024\PullRiph;
use App\Models2024\UserFile;
use Illuminate\Support\Facades\Storage;
use Spatie\Browsershot\Browsershot;

class LogbookController extends Controller
{

	public function index($noIjin)
	{
		// Using the datareport function to get the payload
		$payload = $this->logbookReport($noIjin);

		$mapkey = ForeignApi::find(1);
		// dd($payload);

		// Prepare the directory and file name
		$npwp = str_replace(['.', '-'], '', $payload['npwp']);
		$periode = $payload['periode'];
		$fileName = 'logbook_' .  $noIjin . '_' . '_' . time() . '.pdf';
		$directory = 'uploads/' . $npwp . '/' . $periode . '/' . $noIjin;
		$path = $directory . '/' . $fileName;

		// Render the HTML template with payload data
		$template = view('t2024.logbook.index', [
			'payload' => $payload,
			'mapkey' => $mapkey,
			// 'npwp' => $npwp,
			// 'periode' => $periode,
			])->render();
			// $footer = view('t2024.logbook.footer')->render();
		$footer = '
		<div style="margin: 0 auto; text-align: center;">
			<div class="col-12">
				<span class="text-center" style="font-size: 10px;">
					Halaman <span class="pageNumber">@pageNumber</span> dari <span class="totalPages">@totalPages</span>
					|| Autogenerated. Dicetak pada ' . now()->format('d M Y H:i:s') . '
				</span>
			</div>
		</div>';



		UserFile::updateOrCreate(
			[
				'no_ijin' => $payload['noIjin'],
				'kind' => 'logbook',
			],
			[
				'file_code' => $fileName,
				'file_url' => url($path),
			]
		);

		// foreach ($payload['lokasis'] as $lokasi) {
		// 	$mapUrl = "https://maps.googleapis.com/maps/api/staticmap?center={$lokasi->spatial->latitude},{$lokasi->spatial->longitude}&zoom=18&size=600x300&maptype=satellite&key={$mapkey->key}";
		// 	$mapImagePath = 'uploads/' . $npwp . '/' . $periode . '/' . $noIjin . '/map_' . $lokasi->kode_spatial . '.png';

		// 	// Download the image and save it locally
		// 	Storage::disk('public')->put($mapImagePath, file_get_contents($mapUrl));
		// }

		if (!Storage::disk('public')->exists($directory)) {
			Storage::disk('public')->makeDirectory($directory);
		}

		// Generate the PDF and save it
		Browsershot::html($template)
			->showBrowserHeaderAndFooter()
			->showBackground()
			->footerHtml($footer)
			->margins(4, 0, 4, 0,)
			->format('A4')
			->save(Storage::disk('public')->path($path));

		return redirect()->back()->with('success', 'Berkas berhasil dibuat.');
	}

    public function generateLogbook($noIjin)
	{
		$payload = $this->logbookReport($noIjin);
		$mapkey = ForeignApi::find(1);
		// return $payload;
		return view('t2024.logbook.index', compact('payload', 'mapkey'));
	}

	public function logbookReport($noIjin)
	{
		$ijin = $noIjin;
		$noIjin = substr($noIjin, 0, 4) . '/' .
			substr($noIjin, 4, 2) . '.' .
			substr($noIjin, 6, 3) . '/' .
			substr($noIjin, 9, 1) . '/' .
			substr($noIjin, 10, 2) . '/' .
			substr($noIjin, 12, 4);

		$commitment = PullRiph::where('no_ijin', $noIjin)->first();
		$lokasis = Lokasi::where('no_ijin', $noIjin)
		->with([
			'pullriph' => function ($query){
				$query->select(
					'id',
					'nama',
					'no_ijin'
				);
			}
		])
		->get() ?? new Lokasi();
		$userFiles = UserFile::where('no_ijin', $noIjin)->first() ?? new UserFile();

		$payload = [
			'company' => $commitment->datauser->company_name,
			'npwp' => $commitment->datauser->npwp_company,
			'ijin' => $ijin,
			'noIjin' => $commitment->no_ijin,
			'periode' => $commitment->periodetahun,
			'lokasis' => $lokasis,
			'userFiles' => $userFiles,
		];

		return $payload;
	}
}
